### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by coco66688** [rohanrkamath/galaxy_bot#2]
Unhandled promise rejection: MongoParseError: Invalid connection string
    at parseConnectionString (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongodb\lib\core\uri_parser.js:573:21)
    at connect (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongodb\lib\operations\connect.js:281:3)
    at C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongodb\lib\mongo_client.js:256:5
    at maybePromise (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongodb\lib\utils.js:685:3)
    at MongoClient.connect (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongodb\lib\mongo_client.js:252:10)
    at C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\connection.js:835:12
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\connection.js:832:19)
    at C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\index.js:350:10
    at C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\index.js:1154:10)
    at Mongoose.connect (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\node_modules\mongoose\lib\index.js:349:20)
    at Object.init (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\Utils\mongoose.js:5:14)
    at Object.<anonymous> (C:\Users\user\Downloads\galaxy_bot-main\galaxy_bot-main\index.js:419:17)

**Comment by coco66688** [comment]
@rohanrkamath

**Comment by idk-pixel** [comment]
@sam920829 Your MongoDB connection string is incorrect.

**Comment by rohanrkamath** [comment]
Hey @sam920829 

Like @idk-pixel  correctly pointed out, your connections are wrong. Please make sure you are entering the correct cluster name and password string. Although I have not implemented this in my code base, I would suggest you to make a .dotenv file and export it into the file where you have written the mongoose ORM settings. This way you do not have to go through the trouble of abstracting the mongoose file where you have stored your credentials in. 

Sorry for the delayed reply.
